# Goal
string desired_state

## Move 2 point params
LatLong position
float64 depth

## Path following params
string path_mode
float64 spiral_diameter
float64 spiral_increment
float64 resume_path_from_progress #[0, 1]

---
# Result
bool success
string message

---
# Feedback
string status_message
float64 path_following_progress #[0, 1]
