# Mission control parameters for the AUV
ctrl_rate = 2; // Hz
startFromTask = 4;

# Mission parameters
delay_mission_start = 5.0; // s, delay before the mission starts

depth_tolerance = 0.3; // m, tolerance for the depth control
latlong_tolerance = 0.5; // m, tolerance for the latlong control

ignore_buoy_color = true; // for gate recognition
gate_wps_distance = 2.5; // m, distance from the gate waypoints to the gate center for the wps generation

use_starting_depth_as_surface_depth = true; 
surface_depth = 0.2;
dive_depth = 0.5; 
dive_depth_buoys = 2.4; 
dive_depth_gate = 1.2; 
dive_depth_manipulation_console = 2.8; 

# Debug parameters
simulate_kcl = true;
simulate_bridge = true;
simulate_perception = false;
simulate_ctrl_station = true;
debug_prints = true;
			
localization_timeout = 10.0;
inspect_buoy_orbiting_timeout = 10.0; // s, timeout for the buoy inspection orbiting
inspect_buoy_orbiting_radius = 1.0; // m, radius for the buoy inspection orbiting

system_status_timeout=2;
homing_state_timeout=9999 ; 			
move_to_wp_state_timeout=9999;			
search_for_object_state_timeout=9999;	 		
cross_gate_state_timeout=9999; 		
search_buoy_area_state_timeout=9999; 			
inspect_buoy_state_timeout=9999;
inspect_pipe_state_timeout=9999;
update_localization_state_timeout=5;

goal_positions = (
					{
						point = [44.0958890, 9.8643269, 3.4]; 
					}
					,{
						point = [44.0958674, 9.8643229, 3.4]; 
					}
					,{
						point = [44.0957980, 9.8643969, 1.2]; 
					}
					,{
						point = [44.0957498, 9.8644933, 1.2];
					}
					,{
						point = [44.0957253, 9.8645846, 2.4];
					}
					,{
						point = [0.0, 0.0, 0.0];
					}
				)

use_debug_gate = true;
debug_gate_position = (
					{
            			point = [44.0958763, 9.8648385];
					},
					{
						point = [44.222222, 9.222222];
					}
				)

use_debug_buoys = true;
debug_buoys_position = (
					{
						point = [44.0958763, 9.8648385];
					},
					{
						point = [44.222222, 9.222222];
					}
				)
				

debug_position_selection = 0; // 0 to skip the action, 1,2,3 ecc for the debug positions defined below
debug_positions = (
					{
            			point = [44.0958763, 9.8648385];
					},
					{
						point = [44.222222, 9.222222];
					}
				)


# buoysDebug = false;
# buoysStonefishPositions = (
# 					# {
# 					# 	point = [13.0, 0.0];
# 					# }
# 					# ,{
# 					# 	point = [13.000, 2.000];
# 					# }
# 					# ,{
# 					# 	point = [21.0, 5.0]
# 					# }
# 					# ,{
# 					# 	point = [17.0, 3.0]
# 					# }
# 					# ,{
# 					# 	point = [21.0, -2.0]
# 					# }
# 					{
# 						point = [28.0, -4.0]
# 					}
# 					# ,{
# 					# 	point = [26.0, -4.0]
# 					# }

# 				)

# to do
max_pipe_inspection_laps = 3; 
