#TO DO with samu
# Request part of the service


# For Path Following 2D Serpentine
float64 serpentine_angle           # Angle of the serpentine path
bool serpentine_direction          # Direction of the serpentine path; true=FORWARD, false=BACKWARD
float64 serpentine_offset          # Offset for the serpentine path
geometry_msgs/Vector3[] serpentine_polygon_vertices # Polygon vertices for the serpentine path
float64 curvature                  # Curvature of the serpentine path

---
# Response part of the service
bool success         # Whether the operation was successful
