tbm = 1;
pipelineStructures = (
	     				{  
							centroid = [44.11, 9.11]; 
						},
	     				{  
							centroid = [44.22, 9.22]; 
						} 
					);

enableBuoysArea = true;
buoysAreaCentroid = [ 44.1111, 9.1111] ;
buoysAreaSize = [10.0, 10.0];
buoysAreaOrientation = 1.57;
