mqtt_address=tcp://localhost:1883
#mqtt_address=tcp://130.251.6.23:1883
client_id=ros2_client
username=teamA
password=passwordA
topic_update=catl/rami25/sectorA/update
topic_status=catl/rami25/sectorA/status
qos=1

