#mqtt_address=tcp://localhost:1883
mqtt_address=tcp://192.168.1.10:1883
client_id=ros2_client
username=unige
password=unige9759
topic_update=catl/rami25/sector_2/update
topic_status=catl/rami25/sector_2/status
qos=1

