simulate_kcl = true;
simulate_bridge = true;
simulate_perception = true;
simulate_ctrl_station = true;
debug_prints = true;

depth_tolerance = 0.5;
latlong_tolerance = 0.5;
ctrl_rate = 1; // Hz
bridge_liveness_timeout = 2.0; // s
perception_liveness_timeout = 2.0; // s
kcl_liveness_timeout = 2.0; // s
system_liveness_timeout = 5.0; // s, time after which the mission is considered failed if no liveness is received from all components


# to do
max_pipe_inspection_laps = 3; 
max_localization_on_surface_time = 10.0;

