tbm = 3; 
pipelineStructures = (
	     				{  
							centroid = [44.11, 9.11]; 
						},
	     				{  
							centroid = [44.22, 9.22]; 
						} 
					);


buoysArea = (
	{
		point = [44.0957980, 9.8643969];
	}
	,{
		point = [44.0958398, 9.8643514];
	}
	,{
		point = [44.0958516, 9.8644309];
	}
	,{
		point = [44.0958073, 9.8644822];
	}
)
manipulationArea = (
	{
		point = [44.0957253, 9.8645846];
	}
	,{
		point = [44.0957592, 9.8645428];
	}
	,{
		point = [44.0957829, 9.8645898];
	}
	,{
		point = [44.0957502, 9.8646338];
	}
)


uavWaypoint = [44.0957522, 9.8646867]; #TBMs 1
selectedPipelineStructureId = 1; #TBMs 1, 2, 3
numberOfMainPipeDamageMarkers = 2; #TBMs 2, 3
numberOfBuoys = 1; #TBMs 1, 3
buoysActions =  {#color 0=white, 1=yellow, 2=red, 3=black
					clockWiseRotation = "white"; 
					counterClockWiseRotation = "yellow";
					goUp = "red";
					goDown = "black";
				}; #TBMs 1, 3
pipelinePipes = (
				{  number = 3;
					orientation = 1.57;
					centroid = [44.11, 9.11]; 
				},
				
				{  number = 4;
					orientation = 3.14;
					centroid = [44.11, 9.22]; 
				}
			); #TBMs 1, 3
damagedPipeOnPipeline = {  
							number = 2;
							orientation = 1.57;
							centroid = [44.11, 9.11]; 
						}; #TBM 2
		





