tbm = 2; 
pipelineStructures = (
	     				{  
							centroid = [44.11, 9.11]; 
						},
	     				{  
							centroid = [44.22, 9.22]; 
						} 
					);

buoysArea = (
	{
		point = [44.09603149970535, 9.864963521542272];
	}
	,{
		point = [44.09587993449084, 9.86504496215988];
	}
	,{
		point = [44.095852596029225, 9.864842899911254];
	}
	,{
		point = [44.095993835906334, 9.864800944994819];
	}
)

uavWaypoint = [44.095884874040344, 9.864938969313851]; #TBMs 1
selectedPipelineStructureId = 1; #TBMs 1, 2, 3
numberOfMainPipeDamageMarkers = 2; #TBMs 2, 3
numberOfBuoys = 1; #TBMs 1, 3
buoysActions =  {#color 0=white, 1=yellow, 2=red, 3=black
					clockWiseRotation = "white"; 
					counterClockWiseRotation = "yellow";
					goUp = "red";
					goDown = "black";
				}; #TBMs 1, 3
pipelinePipes = (
				{  number = 3;
					orientation = 1.57;
					centroid = [44.11, 9.11]; 
				},
				
				{  number = 4;
					orientation = 3.14;
					centroid = [44.11, 9.22]; 
				}
			); #TBMs 1, 3
damagedPipeOnPipeline = {  
							number = 2;
							orientation = 1.57;
							centroid = [44.11, 9.11]; 
						}; #TBM 2
		





