tbm = 2; 
pipelineStructures = (
	     				{  
							centroid = [44.11, 9.11]; 
						},
	     				{  
							centroid = [44.22, 9.22]; 
						} 
					);

buoysArea = (
	{
		point = [44.0958090, 9.8642437];
	}
	,{
		point = [44.0958322, 9.8642136];
	}
	,{
		point = [44.0958564, 9.8642516];
	}
	,{
		point = [44.0958313, 9.8642835];
	}
)


uavWaypoint = [44.0957522, 9.8646867]; #TBMs 1
selectedPipelineStructureId = 1; #TBMs 1, 2, 3
numberOfMainPipeDamageMarkers = 2; #TBMs 2, 3
numberOfBuoys = 1; #TBMs 1, 3
buoysActions =  {#color 0=white, 1=yellow, 2=red, 3=black
					clockWiseRotation = "white"; 
					counterClockWiseRotation = "yellow";
					goUp = "red";
					goDown = "black";
				}; #TBMs 1, 3
pipelinePipes = (
				{  number = 3;
					orientation = 1.57;
					centroid = [44.11, 9.11]; 
				},
				
				{  number = 4;
					orientation = 3.14;
					centroid = [44.11, 9.22]; 
				}
			); #TBMs 1, 3
damagedPipeOnPipeline = {  
							number = 2;
							orientation = 1.57;
							centroid = [44.11, 9.11]; 
						}; #TBM 2
		





