mavlink_bridge:
  ros__parameters:
    config_name: bridge
    camera_enabled: true
    camera_source_uri: udp://192.168.2.3:5600
    camera_rtp_caps: application/x-rtp, media=video, encoding-name=H264, payload=96, clock-rate=90000
    camera_topic: /auv/camera/image_raw
    camera_info_topic: /auv/camera/camera_info
    camera_frame_id: camera_optical_frame
    camera_use_hw_decoder: true
    camera_qos_reliable: false
    camera_enable_max_performance: true
    camera_preview_width: 960
    camera_preview_height: 540
    camera_preview_max_fps: 15.0
    camera_output_encoding: rgba8
    camera_info_publish_rate_hz: 2.0
    camera_rtp_latency_ms: 75
    camera_udp_buffer_size_bytes: 2097152
    camera_appsink_max_buffers: 1
    camera_appsink_drop: true
    camera_pipeline_override: ""
