DynamicGoalBasedALOS:
{
    gainsDelta = [0.0, 8.0, 0.0, 0.0 ,0.0, 0.1];   # Kp, Ki, Kd, Kff, N, Tr   
    deltaMin = 0.5;
    deltaMax = 2.5;
    dt = 0.01;

    gamma_crosstrack = 0.0;
    gamma_verticaltrack = 0.0;

    epsilon = 0.000001;

    betaHat_c_max = 0.4;
    betaHat_c_min = -0.4;
    thetaHat_c_max = 0.4;
    thetaHat_c_min = -0.4;

    crossTrackErrorWeight = 1.0;
    verticalTrackErrorWeight = 5.0;
    tangentsDifferenceNormWeight = 30.0;

    betaHat_c_init = 0.0;
    thetaHat_c_init = 0.0;
};
