BlueROV:
{
    # Thruster limits (ensuring correct type and number of elements)
    thruster_upper_limits: [70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0]; # N
    thruster_lower_limits: [-60.0, -60.0, -60.0, -60.0, -60.0, -60.0, -60.0, -60.0]; # N
    thruster_allocation_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]; # Even distribution

    # params for BlueROV STIL
    # gainsX: [0.5, 0.0, 0.0, 0.0, 0.0, 0.01]; # Kp, Ki, Kd, Kff, N, Tr 
    # gainsY: [0.5, 0.0, 0.0, 0.0, 0.0, 0.01]; 
    # gainsZ: [0.5, 0.0, 0.0, 0.0, 0.0, 0.01];
    # gainsRoll: [1.0, 0.0, 0.0, 0.0, 0.0, 0.01];
    # gainsPitch: [1.0, 0.0, 0.0, 0.0, 0.0, 0.01];
    # gainsYaw: [1.0, 0.0, 0.0, 0.0, 0.0, 0.01];

    # params for BlueROV gazebo
    gainsX: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]; # Kp, Ki, Kd, Kff, N, Tr 
    gainsY: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]; 
    gainsZ: [0.5, 0.0, 0.0, 0.0, 0.0, 0.0];
    gainsRoll: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0];
    gainsPitch: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0];
    gainsYaw: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0];

    # #Max and Min linear & angular velocities
    max_linear_angular_velocities: [2.0, 1.8, 0.55, 2.0, 2.2, 1.85]; # m/s, rad/s
    min_linear_angular_velocities: [-2.0, -1.8, -0.55, -2.0, -2.2, -1.85]; # m/s, rad/s
    
};

