bridge:
{   
    # Remote address
    remote_addr = "127.0.0.1";

    # MAVLink system and component IDs
    system_id = 255;            // (255 = ground station)
    component_id = 190;        

    # MAVLink port
    port = 14551;
}