bridge:
{   
<<<<<<< HEAD
    simulation_mode = false ;
=======
    simulation_mode = true ;
>>>>>>> 25fc5a9c23ae743c5d4fda9408a67ea02b260074
    # Remote address
    remote_addr = "192.168.2.2";

    # MAVLink system and component IDs
    system_id = 42;            
    component_id = 190;        

    # MAVLink port
    port = 14558;
}
