# Mission control parameters for the AUV
ctrl_rate = 1; // Hz

# Mission parameters
delay_mission_start = 5.0; // s, delay before the mission starts
ignore_buoy_color = true; // for gate recognition
gate_wps_distance = 2.5; // m, distance from the gate waypoints to the gate center for the wps generation
depth_tolerance = 0.3; // m, tolerance for the depth control
latlong_tolerance = 0.5; // m, tolerance for the latlong control
localization_timeout = 10.0;
inspect_buoy_orbiting_timeout = 10.0; // s, timeout for the buoy inspection orbiting
inspect_buoy_orbiting_radius = 1.0; // m, radius for the buoy inspection orbiting

use_starting_depth_as_surface_depth = true; 
surface_depth = 0.2;
dive_depth = 1.5; 
dive_depth_buoys = 2.4; 
dive_depth_gate = 1.2; 
dive_depth_manipulation_console = 2.8; 

# Debug parameters
simulate_kcl = false;
simulate_bridge = false;
simulate_perception = false;
simulate_ctrl_station = true;
debug_prints = true;
debug_position_selection = 2; // 0 to skip the action, 1,2,3 ecc for the debug positions defined below
			
homing_state_timeout=9999 ; 			
move_to_wp_state_timeout=9999;			
search_for_object_state_timeout=9999;	 		
cross_gate_state_timeout=9999; 		
search_buoy_area_state_timeout=9999; 			
inspect_buoy_state_timeout=9999;
inspect_pipe_state_timeout=9999;
update_localization_state_timeout=5;


debug_positions = (
					{
            point = [44.09594124559377, 9.864530289935066];
					},
          {
						point = [44.0960618, 9.8650092];
          }
					# ,{
					# 	point = [44.095848278311, 9.86479295206827]; //manipulation console position
					# }
					# ,{
					# 	point = [44.0958532388666, 9.864816960827]; //pipestruct
					# }
					# ,{
					# 	point = [18.0, 5.0];
					# }
					# ,{
					# 	point = [15.0, 6.0];
					# }
					# ,{
					# 	point = [16.0, 8.0];
					# }
				)

buoysDebug = true;
buoysStonefishPositions = (
					# {
					# 	point = [13.0, 0.0];
					# }
					# ,{
					# 	point = [13.000, 2.000];
					# }
					# ,{
					# 	point = [21.0, 5.0]
					# }
					# ,{
					# 	point = [17.0, 3.0]
					# }
					# ,{
					# 	point = [21.0, -2.0]
					# }
					{
						point = [28.0, -4.0]
					}
					# ,{
					# 	point = [26.0, -4.0]
					# }

				)

# to do
max_pipe_inspection_laps = 3; 
