# Mission control parameters for the AUV
ctrl_rate = 1; // Hz

# System components checks
bridge_liveness_timeout = 2.0; // s
perception_liveness_timeout = 2.0; // s
kcl_liveness_timeout = 2.0; // s


# Mission parameters
ignore_buoy_color = true; // for gate recognition
gate_wps_distance = 2.5; // m, distance from the gate waypoints to the gate center for the wps generation
depth_tolerance = 0.5; // m, tolerance for the depth control
latlong_tolerance = 0.5; // m, tolerance for the latlong control
safety_area_timeout = 200.0;
localization_timeout = 10.0;

safetyBoundary = (
					{
						point = [44.096081710077144, 9.864995954761016]; #North basin corner
					}
					,{
						point = [44.09574783122071, 9.865156880335148]; #South basin corner
					}
					,{
						point = [44.095609325556396, 9.864546321190707]; #SouthWest basin limit
					}
					,{
						point = [44.09594226946521, 9.8644151125183];	 #NorthWest basin limit
					}
				)


# Debug parameters
simulate_kcl = false;
simulate_bridge = false;
simulate_perception = true;
simulate_ctrl_station = true;
debug_prints = true;
debugPosition = [44.09587659752644, 9.864977900600218];

buoysDebug = true;
buoysStonefishPositions = (
					{
						point = [13.0, 2.0];
					}
					,{
						point = [13.000, 4.000];
					}
					# ,{
					# 	point = [18.000, 3.000];
					# }
					# ,{
					# 	point = [18.0, 5.0];
					# }
					# ,{
					# 	point = [15.0, 6.0];
					# }
					# ,{
					# 	point = [16.0, 8.0];
					# }
				)

# to do
max_pipe_inspection_laps = 3; 
