check_rate = 1; #Hz

mission_ctrl_timeout = 5.0; #s
bridge_timeout = 2.0; #s
kcl_timeout = 2.0; #s
perception_timeout = 5.0; #s
vehicle_to_safety_area_timeout = 1.0; #s

safetyBoundary = (
					{
						point = [44.096081710077144, 9.864995954761016]; #North basin corner
					}
					,{
						point = [44.09574783122071, 9.865156880335148]; #South basin corner
					}
					,{
						point = [44.095609325556396, 9.864546321190707]; #SouthWest basin limit
					}
					,{
						point = [44.09594226946521, 9.8644151125183];	 #NorthWest basin limit
					}
				)

